name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: spbalis/taskmanager:latest

      - name: ArgoCD App Sync
        if: ${{ success() }}
        run: |
          curl -k -X POST https://localhost:8081/api/v1/applications/taskmanager/sync \
            -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{}'
